# Generated by Django 6.0.6 on 2026-06-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
    ]
